source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LIFXAPIWrapper_Example', :exclusive => true do
  pod "LIFXAPIWrapper", :path => "../"
end

target 'LIFXAPIWrapper_Tests', :exclusive => true do
  pod "LIFXAPIWrapper", :path => "../"

  
end
